# Generated by Django 4.2.3 on 2023-07-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PriorAuthRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurance_provider", models.TextField(blank=True, null=True)),
                ("insurance_plan_number", models.TextField(blank=True, null=True)),
                ("insurance_coverage_state", models.TextField(blank=True, null=True)),
                ("medication", models.TextField(blank=True, null=True)),
                ("requirements_flow", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "requirements__prior_auth_requirement",
                "abstract": False,
            },
        ),
    ]
