# Generated by Django 4.2.3 on 2023-07-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priorauthrequirement",
            name="insurance_coverage_state",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="priorauthrequirement",
            name="insurance_plan_number",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="priorauthrequirement",
            name="insurance_provider",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="priorauthrequirement",
            name="medication",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
