# Generated by Django 4.2.4 on 2023-09-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_remove_memberdetails_ma_email_priorauthdenial_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="client_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user",
                to="portal.clientcompany",
            ),
        ),
    ]
