# Generated by Django 4.2.3 on 2023-07-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_add_trigram"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorauthrequirement",
            name="requirements_checklist",
            field=models.JSONField(null=True),
        ),
    ]
