# Generated by Django 4.2.4 on 2023-09-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_alter_user_client_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorauthrequirement",
            name="smart_engine_checklist",
            field=models.JSONField(null=True),
        ),
    ]
