# Generated by Django 4.2.3 on 2023-07-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0004_priorauthrequirement_requirements_checklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorauthrequirement",
            name="description",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="priorauthrequirement",
            name="url_slug",
            field=models.TextField(db_index=True, editable=False, null=True, unique=True),
        ),
    ]
