# Generated by Django 4.2.3 on 2023-08-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_priorauthrequirement_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorauthrequirement",
            name="requirements_flow_file_location",
            field=models.TextField(blank=True, null=True),
        ),
    ]
