# Generated by Django 4.2.5 on 2023-09-20 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0006_alter_priorauthdenial_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientcompany",
            options={
                "verbose_name": "Client Company",
                "verbose_name_plural": "Client Companies",
            },
        ),
    ]
