# Generated by Django 4.2.5 on 2023-09-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0006_alter_clientcompany_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceEmailLogAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.TextField(
                        choices=[
                            ("More Info Request", "New Request"),
                            ("Denial Details Submitted", "Denial"),
                            ("Password Reset", "Password Reset"),
                            ("User Activation", "Activation"),
                            ("Domain Not Registered", "Not Registered Promo"),
                            ("Ran Out of Seats", "Ran Out Of Seats"),
                        ]
                    ),
                ),
                ("email_to", models.JSONField()),
                ("email_body", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics__service_email_log_action",
                "abstract": False,
            },
        ),
    ]
