# Generated by Django 4.2.4 on 2023-08-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0007_priorauthrequirement_insurance_plan_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="priorauthrequirement",
            name="id",
        ),
        migrations.AlterField(
            model_name="priorauthrequirement",
            name="url_slug",
            field=models.TextField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
