# Generated by Django 4.2.5 on 2023-09-26 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0007_serviceemaillogaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriorAuthSubmission",
            fields=[
                (
                    "cover_my_meds_key",
                    models.TextField(db_index=True, primary_key=True, serialize=False),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements_alignment_completion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "requirements__prior_auth_submission",
                "abstract": False,
            },
        ),
    ]
