# Generated by Django 4.2.5 on 2023-10-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0008_priorauthsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "medication_name",
                    models.TextField(db_index=True, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "requirements__medication",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirement_rule_set", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "requirements__requirement",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RequirementOptionTemplate",
            fields=[
                (
                    "option_rule_name",
                    models.TextField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "node_type",
                    models.TextField(
                        choices=[("radio", "Radio"), ("checkbox", "Checkbox")],
                        default="radio",
                    ),
                ),
                ("label", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "requirements__requirement_option_template",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RequirementTemplate",
            fields=[
                (
                    "requirement_rule_name",
                    models.TextField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "node_type",
                    models.TextField(
                        choices=[("fieldset", "Fieldset")], default="fieldset"
                    ),
                ),
                ("label", models.TextField(blank=True, null=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_templates",
                        to="portal.medication",
                    ),
                ),
            ],
            options={
                "db_table": "requirements__requirement_template",
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="priorauthrequirement",
            name="requirements_checklist",
        ),
        migrations.RemoveField(
            model_name="priorauthrequirement",
            name="smart_engine_checklist",
        ),
        migrations.CreateModel(
            name="SmartEngineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField(blank=True, null=True)),
                ("validation", models.TextField(blank=True, null=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_engine_items",
                        to="portal.medication",
                    ),
                ),
                (
                    "requirement_option_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_engine_items",
                        to="portal.requirementoptiontemplate",
                    ),
                ),
                (
                    "requirement_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_engine_items",
                        to="portal.requirementtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "requirements__smart_engine_item",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="requirementoptiontemplate",
            name="requirement_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirement_option_templates",
                to="portal.requirementtemplate",
            ),
        ),
        migrations.CreateModel(
            name="RequirementOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_rule_set", models.JSONField(blank=True, null=True)),
                (
                    "prior_auth_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_options",
                        to="portal.priorauthrequirement",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_options",
                        to="portal.requirement",
                    ),
                ),
                (
                    "requirement_option_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_options",
                        to="portal.requirementoptiontemplate",
                    ),
                ),
                (
                    "smart_engine_items",
                    models.ManyToManyField(
                        related_name="requirement_options", to="portal.smartengineitem"
                    ),
                ),
            ],
            options={
                "db_table": "requirements__requirement_option",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="requirement",
            name="prior_auth_requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="portal.priorauthrequirement",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="requirement_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="portal.requirementtemplate",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="smart_engine_items",
            field=models.ManyToManyField(
                related_name="requirements", to="portal.smartengineitem"
            ),
        ),
        migrations.AlterField(
            model_name="priorauthrequirement",
            name="medication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prior_auth_requirements",
                to="portal.medication",
            ),
        ),
    ]
