# Generated by Django 4.2.4 on 2023-08-10 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0008_remove_priorauthrequirement_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorauthrequirement",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="priorauthrequirement",
            name="date_modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
