# Generated by Django 4.2.5 on 2023-09-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0009_rename_submission_date_uxfeedback_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceemaillogaction",
            name="email_type",
            field=models.TextField(
                choices=[
                    ("More Info Request", "New Request"),
                    ("Denial Details Submitted", "Denial"),
                    ("Password Reset", "Password Reset"),
                    ("User Activation", "Activation"),
                    ("Domain Not Registered", "Not Registered Promo"),
                    ("Ran Out of Seats", "Ran Out Of Seats"),
                    ("Negative UX Feedback", "Negative Ux Feedback"),
                ]
            ),
        ),
    ]
