# Generated by Django 4.2.4 on 2023-08-12 10:12

from django.db import migrations, models
import django.db.models.deletion
import portal.models.field


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0009_priorauthrequirement_date_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", portal.models.field.AES256EncryptedField()),
                ("last_name", portal.models.field.AES256EncryptedField()),
                ("dob", portal.models.field.AES256EncryptedField()),
                ("email", portal.models.field.AES256EncryptedField()),
                ("member_id", portal.models.field.AES256EncryptedField()),
                ("phone_number", portal.models.field.AES256EncryptedField()),
                ("address", portal.models.field.AES256EncryptedField()),
                ("referring_doctor", portal.models.field.AES256EncryptedField()),
                ("ma_email", portal.models.field.AES256EncryptedField()),
            ],
            options={
                "db_table": "requirements__member_details",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PriorAuthDenial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication", models.TextField(blank=True, null=True)),
                ("cover_my_meds_key", models.TextField(blank=True, null=True)),
                ("ma_email", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pa_denial__prior_auth_denial",
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="priorauthrequirement",
            name="insurance_plan_number",
        ),
        migrations.RemoveField(
            model_name="priorauthrequirement",
            name="requirements_flow",
        ),
        migrations.RemoveField(
            model_name="priorauthrequirement",
            name="requirements_flow_file_location",
        ),
        migrations.CreateModel(
            name="UXFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("release_version", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                (
                    "prior_auth_requirements",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.priorauthrequirement",
                    ),
                ),
            ],
            options={
                "db_table": "user_experience__ux_feedback",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RequestNewPriorAuthRequirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication", models.TextField(blank=True, null=True)),
                ("insurance_provider", models.TextField(blank=True, null=True)),
                ("insurance_coverage_state", models.TextField(blank=True, null=True)),
                ("insurance_plan_type", models.TextField(blank=True, null=True)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("release_version", models.TextField(blank=True, null=True)),
                (
                    "member_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.memberdetails",
                    ),
                ),
            ],
            options={
                "db_table": "requirements__request_new_prior_auth_requirements",
                "abstract": False,
            },
        ),
    ]
