# Generated by Django 4.2.4 on 2023-08-11 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0010_memberdetails_priorauthdenial_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uxfeedback",
            name="requirements_date_modified",
        ),
    ]
