# Generated by Django 4.2.4 on 2023-08-16 09:58

from django.db import migrations
import portal.models.field


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0010_memberdetails_priorauthdenial_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberdetails",
            name="address",
        ),
        migrations.RemoveField(
            model_name="memberdetails",
            name="email",
        ),
        migrations.RemoveField(
            model_name="memberdetails",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="memberdetails",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="memberdetails",
            name="referring_doctor",
        ),
        migrations.RemoveField(
            model_name="requestnewpriorauthrequirements",
            name="insurance_plan_type",
        ),
        migrations.AddField(
            model_name="memberdetails",
            name="cover_my_meds_key",
            field=portal.models.field.AES256EncryptedField(),
        ),
    ]
