# Generated by Django 4.2.4 on 2023-08-16 13:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0011_remove_memberdetails_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="priorauthdenial",
            name="cover_my_meds_key",
        ),
        migrations.RemoveField(
            model_name="priorauthdenial",
            name="ma_email",
        ),
        migrations.AddField(
            model_name="priorauthdenial",
            name="member_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portal.memberdetails",
            ),
        ),
        migrations.AddField(
            model_name="priorauthdenial",
            name="release_version",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="priorauthdenial",
            name="submission_date",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
