# Generated by Django 4.2.5 on 2023-10-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0011_insurancecoveragecriteria_insuranceplantype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requirement",
            name="requirement_rule_set",
        ),
        migrations.RemoveField(
            model_name="requirementoption",
            name="option_rule_set",
        ),
        migrations.AddField(
            model_name="requirement",
            name="requirement_rule_set",
            field=models.ManyToManyField(
                db_table="requirements__requirementtemplate_to_requirement",
                related_name="+",
                to="portal.requirementtemplate",
            ),
        ),
        migrations.AddField(
            model_name="requirementoption",
            name="option_rule_set",
            field=models.ManyToManyField(
                db_table="requirements__requirementoptiontemplate_to_requirement",
                related_name="+",
                to="portal.requirementoptiontemplate",
            ),
        ),
    ]
