# Generated by Django 4.2.5 on 2023-10-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0012_remove_requirement_requirement_rule_set_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancecoveragecriteria",
            name="insurance_plan_types",
            field=models.ManyToManyField(
                blank=True,
                db_table="requirements__insuranceplantype_to_insurancecoveragecriteria",
                related_name="insurance_coverage_criteria",
                to="portal.insuranceplantype",
            ),
        ),
        migrations.AlterField(
            model_name="insurancecoveragecriteria",
            name="states",
            field=models.ManyToManyField(
                blank=True,
                db_table="requirements__state_to_insurancecoveragecriteria",
                related_name="insurance_coverage_criteria",
                to="portal.state",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="requirement_rule_set",
            field=models.ManyToManyField(
                blank=True,
                db_table="requirements__requirementtemplate_to_requirement",
                related_name="+",
                to="portal.requirementtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="smart_engine_items",
            field=models.ManyToManyField(
                blank=True,
                db_table="requirements__smartengineitem_to_requirement",
                related_name="+",
                to="portal.smartengineitem",
            ),
        ),
        migrations.AlterField(
            model_name="requirementoption",
            name="option_rule_set",
            field=models.ManyToManyField(
                blank=True,
                db_table="requirements__requirementoptiontemplate_to_requirement",
                related_name="+",
                to="portal.requirementoptiontemplate",
            ),
        ),
        migrations.AlterField(
            model_name="requirementoption",
            name="smart_engine_items",
            field=models.ManyToManyField(
                blank=True,
                db_table="requirements__smartengineitem_to_requirement_option",
                related_name="+",
                to="portal.smartengineitem",
            ),
        ),
    ]
