# Generated by Django 4.2.4 on 2023-08-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0013_priorauthdenial_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorauthrequirement",
            name="smart_engine_checklist",
            field=models.JSONField(null=True),
        ),
    ]
